version: "3.8"

services:
  postgres:
    image: postgres
    container_name: mosaicq_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: building_mosaic
